export const demoLabels = {
  flowField: 'gesture',
  pixelGrid: 'thirty-two by eighteen',
  sorting: 'order learns to dance',
  cellular: 'rules become weather',
  poetry: 'machine with a mood',
  garden: 'a tree remembers every choice',
  shader: 'light from arithmetic',
  type: 'letters as bodies',
  pathfinding: 'the maze has opinions',
  source: 'change the spell',
  diffusion: 'chemistry as draftsman',
  cosmos: 'phyllotaxis cosmos',
  lens: 'a camera that reads the room',
  spectrum: 'drone made visible',
  attractor: 'phase space cosmonaut',
  pond: 'a pond remembers every touch',
}
